---
- name: Set epel-release package name for RHEL
  set_fact:
    epel_package:
      - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
  when: ansible_distribution == 'RedHat'

- name: Set epel-release package name for OracleLinux
  set_fact:
    epel_package:
      - epel-release
  when: ansible_distribution == 'OracleLinux' or ansible_distribution == 'CentOS'

- name: Install epel-release
  become: yes
  become_method: sudo
  ansible.builtin.dnf:
    name: "{{ epel_package }}"
    disable_gpg_check: true
    state: present
  when: epel_package is defined

- name: Enable epel repository
  become: yes
  become_method: sudo
  command:
    argv:
      - yum-config-manager
      - --enable
      - "{{ 'ol' + ansible_facts['distribution_major_version'] + '_developer_EPEL' }}"
  when: ansible_distribution == 'OracleLinux'

- name: Install ktls dependencies
  become: yes
  become_method: sudo
  dnf:
    update_cache: yes
    name: "{{ packages }}"
  retries: 3
  delay: 5
  register: result
  until: result.rc == 0
  vars:
    packages:
      - python3-cryptography
      - ktls-utils
