ifeq (y,$(CONFIG_FSTESTS_BTRFS_ENABLES_RAID56))
FSTESTS_ARGS += fstests_btrfs_enables_raid56=True
endif

ifeq (y,$(CONFIG_FSTESTS_BTRFS_ENABLES_COMPRESSION))

ifeq (y,$(CONFIG_FSTESTS_BTRFS_ENABLES_COMPRESSION_ZLIB))
FSTESTS_ARGS += fstests_btrfs_enables_compression_zlib=True
endif

ifeq (y,$(CONFIG_FSTESTS_BTRFS_ENABLES_COMPRESSION_LZO))
FSTESTS_ARGS += fstests_btrfs_enables_compression_lzo=True
endif

ifeq (y,$(CONFIG_FSTESTS_BTRFS_ENABLES_COMPRESSION_ZSTD))
FSTESTS_ARGS += fstests_btrfs_enables_compression_zstd=True
endif

endif # CONFIG_FSTESTS_BTRFS_ENABLES_COMPRESSION

ifeq (y,$(CONFIG_FSTESTS_BTRFS_ENABLES_HOLES))

FSTESTS_ARGS += fstests_btrfs_enables_holes=True

ifeq (y,$(CONFIG_FSTESTS_BTRFS_SECTION_HOLES))
FSTESTS_ARGS += fstests_btrfs_section_holes=True
endif

ifeq (y,$(CONFIG_FSTESTS_BTRFS_SECTION_HOLES_ZLIB))
FSTESTS_ARGS += fstests_btrfs_section_holes_zlib=True
endif

ifeq (y,$(CONFIG_FSTESTS_BTRFS_SECTION_HOLES_LZO))
FSTESTS_ARGS += fstests_btrfs_section_holes_lzo=True
endif

ifeq (y,$(CONFIG_FSTESTS_BTRFS_SECTION_HOLES_ZSTD))
FSTESTS_ARGS += fstests_btrfs_section_holes_zstd=True
endif

endif # CONFIG_FSTESTS_BTRFS_ENABLES_HOLES

ifeq (y,$(CONFIG_FSTESTS_BTRFS_ENABLES_NOHOLES))

FSTESTS_ARGS += fstests_btrfs_enables_noholes=True

ifeq (y,$(CONFIG_FSTESTS_BTRFS_SECTION_NOHOLES))
FSTESTS_ARGS += fstests_btrfs_section_noholes=True
endif

ifeq (y,$(CONFIG_FSTESTS_BTRFS_SECTION_NOHOLES_ZLIB))
FSTESTS_ARGS += fstests_btrfs_section_noholes_zlib=True
endif

ifeq (y,$(CONFIG_FSTESTS_BTRFS_SECTION_NOHOLES_LZO))
FSTESTS_ARGS += fstests_btrfs_section_noholes_lzo=True
endif

ifeq (y,$(CONFIG_FSTESTS_BTRFS_SECTION_NOHOLES_ZSTD))
FSTESTS_ARGS += fstests_btrfs_section_noholes_zstd=True
endif

endif # CONFIG_FSTESTS_BTRFS_ENABLES_NOHOLES

ifeq (y,$(CONFIG_FSTESTS_BTRFS_ENABLES_FSPACE))

FSTESTS_ARGS += fstests_btrfs_enables_fspace=True

ifeq (y,$(CONFIG_FSTESTS_BTRFS_SECTION_FSPACE))
FSTESTS_ARGS += fstests_btrfs_section_fspace=True
endif

ifeq (y,$(CONFIG_FSTESTS_BTRFS_SECTION_FSPACE_DSYNC))
FSTESTS_ARGS += fstests_btrfs_section_fspace_dsync=True
endif

ifeq (y,$(CONFIG_FSTESTS_BTRFS_SECTION_FSPACE_ZLIB))
FSTESTS_ARGS += fstests_btrfs_section_fspace_zlib=True
endif

ifeq (y,$(CONFIG_FSTESTS_BTRFS_SECTION_FSPACE_LZO))
FSTESTS_ARGS += fstests_btrfs_section_fspace_lzo=True
endif

ifeq (y,$(CONFIG_FSTESTS_BTRFS_SECTION_FSPACE_ZSTD))
FSTESTS_ARGS += fstests_btrfs_section_fspace_zstd=True
endif

endif # CONFIG_FSTESTS_BTRFS_ENABLES_FSPACE

ifeq (y,$(CONFIG_FSTESTS_BTRFS_ENABLES_NOHOFSPACE))

FSTESTS_ARGS += fstests_btrfs_enables_nohofspace=True

ifeq (y,$(CONFIG_FSTESTS_BTRFS_SECTION_NOHOFSPACE))
FSTESTS_ARGS += fstests_btrfs_section_nohofspace=True
endif

ifeq (y,$(CONFIG_FSTESTS_BTRFS_SECTION_NOHOFSPACE_ZLIB))
FSTESTS_ARGS += fstests_btrfs_section_nohofspace_zlib=True
endif

ifeq (y,$(CONFIG_FSTESTS_BTRFS_SECTION_NOHOFSPACE_LZO))
FSTESTS_ARGS += fstests_btrfs_section_nohofspace_lzo=True
endif

ifeq (y,$(CONFIG_FSTESTS_BTRFS_SECTION_NOHOFSPACE_ZSTD))
FSTESTS_ARGS += fstests_btrfs_section_nohofspace_zstd=True
endif

endif # CONFIG_FSTESTS_BTRFS_ENABLES_NOHOFSPACE

ifeq (y,$(CONFIG_FSTESTS_BTRFS_SECTION_SIMPLE))
FSTESTS_ARGS += fstests_btrfs_section_simple=True
endif

ifeq (y,$(CONFIG_FSTESTS_BTRFS_SECTION_SIMPLE_ZNS))
FSTESTS_ARGS += fstests_btrfs_section_simple_zns=True
endif
