---
- name: Install vagrant and vagrant-plugin-libvirt
  become: yes
  become_method: sudo
  dnf:
    name:
      - vagrant
      - vagrant-libvirt
    state: present

- name: Install the timezone vagrant plugin
  command: "vagrant plugin install vagrant-timezone"
  register: cmd_done
  changed_when: "cmd_done.rc == 0"
