# If you need to use a git subtree, please add it here.
add-kconfig-remote:
	git remote add kconfig https://github.com/mcgrof/kconfig.git

add-kconfig:
	git subtree add --prefix=scripts/kconfig/ kconfig master

refresh-kconfig:
	git fetch kconfig
	git subtree pull --prefix=scripts/kconfig/ kconfig master
