# SPDX-License-Identifier: copyleft-next-0.3.1

POSTFIX_RELAY_HOST:=$(subst ",,$(CONFIG_SETUP_POSTFIX_EMAIL_RELAY_HOST))

POSTFIX_SETUP_ARGS += postfix_relay_host_setup=True
POSTFIX_SETUP_ARGS += postfix_relay_host=$(POSTFIX_RELAY_HOST)
