ifeq (y,$(CONFIG_FSTESTS_XFS_QUOTA_ENABLED))
FSTESTS_ARGS += fstests_xfs_mount_quota_opts='$(CONFIG_FSTESTS_XFS_MOUNT_QUOTA_OPTS)'
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_LOGDEV_ENABLED))
FSTESTS_ARGS += fstests_test_logdev='$(subst ",,$(CONFIG_FSTESTS_TEST_LOGDEV))'
FSTESTS_ARGS_DIRECT += fstests_test_logdev_mkfs_opts='$(subst ",,$(CONFIG_FSTESTS_TEST_LOGDEV_MKFS_OPTS))'
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_CRC))
FSTESTS_ARGS += fstests_xfs_section_crc=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_CRC_LOGDEV))
FSTESTS_ARGS += fstests_xfs_section_crc_logdev=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_CRC_RTDEV))
FSTESTS_ARGS += fstests_xfs_section_crc_rtdev=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_CRC_RTDEV_EXTSIZE_28K))
FSTESTS_ARGS += fstests_xfs_section_crc_rtdev_extsize_28k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_CRC_RTDEV_EXTSIZE_64K))
FSTESTS_ARGS += fstests_xfs_section_crc_rtdev_extsize_64k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_CRC_LOGDEV_RTDEV))
FSTESTS_ARGS += fstests_xfs_section_crc_logdev_rtdev=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_NOCRC))
FSTESTS_ARGS += fstests_xfs_section_nocrc=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_NOCRC_512))
FSTESTS_ARGS += fstests_xfs_section_nocrc_512=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_NOCRC_1K))
FSTESTS_ARGS += fstests_xfs_section_nocrc_1k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_NOCRC_2K))
FSTESTS_ARGS += fstests_xfs_section_nocrc_2k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_NOCRC_4K))
FSTESTS_ARGS += fstests_xfs_section_nocrc_4k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_NOCRC_8K))
FSTESTS_ARGS += fstests_xfs_section_nocrc_8k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_NOCRC_8K_4KS))
FSTESTS_ARGS += fstests_xfs_section_nocrc_8k_4ks=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_NOCRC_16K))
FSTESTS_ARGS += fstests_xfs_section_nocrc_16k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_NOCRC_16K_4KS))
FSTESTS_ARGS += fstests_xfs_section_nocrc_16k_4ks=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_NOCRC_32K))
FSTESTS_ARGS += fstests_xfs_section_nocrc_32k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_NOCRC_32K_4KS))
FSTESTS_ARGS += fstests_xfs_section_nocrc_32k_4ks=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_NOCRC_64K))
FSTESTS_ARGS += fstests_xfs_section_nocrc_64k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_NOCRC_64K_4ks))
FSTESTS_ARGS += fstests_xfs_section_nocrc_64k_4ks=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_REFLINK))
FSTESTS_ARGS += fstests_xfs_section_reflink=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_REFLINK_LOGDEV))
FSTESTS_ARGS += fstests_xfs_section_reflink_logdev=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_REFLINK_1024))
FSTESTS_ARGS += fstests_xfs_section_reflink_1024=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_REFLINK_2K))
FSTESTS_ARGS += fstests_xfs_section_reflink_2k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_REFLINK_4K))
FSTESTS_ARGS += fstests_xfs_section_reflink_4k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_REFLINK_8K))
FSTESTS_ARGS += fstests_xfs_section_reflink_8k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_REFLINK_8K_4KS))
FSTESTS_ARGS += fstests_xfs_section_reflink_8k_4ks=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_REFLINK_16K))
FSTESTS_ARGS += fstests_xfs_section_reflink_16k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_REFLINK_16K_4KS))
FSTESTS_ARGS += fstests_xfs_section_reflink_16k_4ks=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_REFLINK_32K))
FSTESTS_ARGS += fstests_xfs_section_reflink_32k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_REFLINK_32K_4KS))
FSTESTS_ARGS += fstests_xfs_section_reflink_32k_4ks=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_REFLINK_64K))
FSTESTS_ARGS += fstests_xfs_section_reflink_64k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_REFLINK_64K_4KS))
FSTESTS_ARGS += fstests_xfs_section_reflink_64k_4ks=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_REFLINK_NORMAPBT))
FSTESTS_ARGS += fstests_xfs_section_reflink_normapbt=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_REFLINK_DIR_BSIZE_8K))
FSTESTS_ARGS += fstests_xfs_section_reflink_dir_bsize_8k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_BIGBLOCK))
FSTESTS_ARGS += fstests_xfs_section_bigblock=True
endif
