ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_LOGDEV))
FSTESTS_ARGS += fstests_test_logdev='$(subst ",,$(CONFIG_FSTESTS_TEST_LOGDEV))'
FSTESTS_ARGS_DIRECT += fstests_test_logdev_mkfs_opts='$(subst ",,$(CONFIG_FSTESTS_TEST_LOGDEV_MKFS_OPTS))'
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_CRC))
FSTESTS_ARGS += fstests_xfs_section_crc=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_NOCRC))
FSTESTS_ARGS += fstests_xfs_section_nocrc=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_NOCRC_512))
FSTESTS_ARGS += fstests_xfs_section_nocrc_512=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_NOCRC_1K))
FSTESTS_ARGS += fstests_xfs_section_nocrc_1k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_NOCRC_2K))
FSTESTS_ARGS += fstests_xfs_section_nocrc_2k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_NOCRC_4K))
FSTESTS_ARGS += fstests_xfs_section_nocrc_4k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_NOCRC_8K))
FSTESTS_ARGS += fstests_xfs_section_nocrc_8k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_NOCRC_16K))
FSTESTS_ARGS += fstests_xfs_section_nocrc_16k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_NOCRC_32K))
FSTESTS_ARGS += fstests_xfs_section_nocrc_32k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_NOCRC_64K))
FSTESTS_ARGS += fstests_xfs_section_nocrc_64k=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_REFLINK))
FSTESTS_ARGS += fstests_xfs_section_reflink=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_REFLINK_1024))
FSTESTS_ARGS += fstests_xfs_section_reflink_1024=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_REFLINK_NORMAPBT))
FSTESTS_ARGS += fstests_xfs_section_reflink_normapbt=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_LOGDEV))
FSTESTS_ARGS += fstests_xfs_section_logdev=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_RTDEV))
FSTESTS_ARGS += fstests_xfs_section_rtdev=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_RTLOGDEV))
FSTESTS_ARGS += fstests_xfs_section_rtlogdev=True
endif

ifeq (y,$(CONFIG_FSTESTS_XFS_SECTION_BIGBLOCK))
FSTESTS_ARGS += fstests_xfs_section_bigblock=True
endif
