---
- name: Import optional user secret specific variables
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "secret.yml"
      skip: true
  tags: vars

- name: Import optional distribution specific variables
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "{{ ansible_facts['os_family']|lower }}.yml"
      skip: true
  tags: vars

- name: Set the path where we collect our kotd updates
  set_fact:
    kotd_uname_before: "../.kotd.uname-before.txt"
    kotd_uname_after:  "../.kotd.uname-after.txt"
  tags: [ 'vars' ]

- name: Get used target kernel version prior to reving kernel
  tags: [ 'kotd' ]
  command: "uname -r"
  register: uname_cmd

- name: Document used target kernel version prior to reving kernel
  local_action: "shell echo {{ uname_cmd.stdout_lines | regex_replace('\\]') | regex_replace('\\[') }} > {{ kotd_uname_before }}"
  tags: [ 'kotd' ]
  run_once: true

# tasks to setup up repos, register system if needed and install
# preferred devtools packages.
- name: Distribution specific setup
  import_tasks: debian/main.yml
  when:
    - ansible_facts['os_family']|lower == 'debian'
    - devconfig_try_refresh_repos|bool
- import_tasks: suse/main.yml
  when:
    - ansible_facts['os_family']|lower == 'suse'
    - devconfig_try_refresh_repos|bool
- import_tasks: redhat/main.yml
  when:
    - ansible_facts['os_family']|lower == 'redhat'
    - devconfig_try_refresh_repos|bool

- name: Check kernel uname
  tags: [ 'kotd' ]
  debug:
    msg: "Running kernel {{ running_kernel }}"
  vars:
    running_kernel: "{{ uname_cmd.stdout_lines.0 }}"

- name: Get used target kernel version after reving kernel
  tags: [ 'kotd' ]
  command: "uname -r"
  register: uname_cmd

- name: Document used target kernel version after reving kernel
  local_action: "shell echo {{ uname_cmd.stdout_lines | regex_replace('\\]') | regex_replace('\\[') }} > {{ kotd_uname_after }}"
  tags: [ 'kotd' ]
  run_once: true
