ifeq (y,$(CONFIG_FSTESTS_NFS_SECTION_DEFAULT))
FSTESTS_ARGS += fstests_nfs_section_default=True
endif
ifeq (y,$(CONFIG_FSTESTS_NFS_SECTION_V40))
FSTESTS_ARGS += fstests_nfs_section_v40=True
endif
ifeq (y,$(CONFIG_FSTESTS_NFS_SECTION_V3))
FSTESTS_ARGS += fstests_nfs_section_v3=True
endif
