---
- name: Update apt cache
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
  tags: [ 'qemu', 'update-cache' ]

- name: Install qemu build dependencies
  become: yes
  become_method: sudo
  apt:
    name:
      - debhelper-compat
      - glusterfs-common
      - gnutls-dev
      - libaio-dev
      - libasound2-dev
      - libbpf-dev
      - libbrlapi-dev
      - libcacard-dev
      - libcap-ng-dev
      - libcapstone-dev
      - libcurl4-gnutls-dev
      - libdrm-dev
      - libepoxy-dev
      - libfdt-dev
      - libfuse3-dev
      - libgbm-dev
      - libglusterfs-dev
      - libgtk-3-dev
      - libibumad-dev
      - libibverbs-dev
      - libiscsi-dev
      - libjack-dev
      - libjpeg-dev
      - libncurses-dev
      - libnfs-dev
      - libnuma-dev
      - libpixman-1-dev
      - libpmem-dev
      - libpng-dev
      - libpulse-dev
      - librbd-dev
      - librdmacm-dev
      - libsasl2-dev
      - libsdl2-dev
      - libseccomp-dev
      - libslirp-dev
      - libspice-server-dev
      - libssh-dev
      - libudev-dev
      - liburing-dev
      - libusb-1.0-0-dev
      - libusbredirparser-dev
      - libvdeplug-dev
      - libvirglrenderer-dev
      - libvte-2.91-dev
      - libxen-dev
      - libzstd-dev
      - meson
      - nettle-dev
      - ninja-build
      - python3
      - python3-sphinx
      - python3-sphinx-rtd-theme
      - texinfo
      - uuid-dev
      - zlib1g-dev
      - device-tree-compiler
      - fcode-utils
      - xsltproc
    state: present
  tags: [ 'qemu', 'build-deps' ]
