#!/bin/bash

MIN_REQ="2.13.4"
OWN_BIN="ansible-playbook"
OWN_VER=$($OWN_BIN --version | head -1 | awk '{print $(NF)'}  | sed -e 's|]||g')

MIN_REQ_LD=$(echo $MIN_REQ | ${TOPDIR}/scripts/ld-version.sh)
OWN_VER_LD=$(echo $OWN_VER | ${TOPDIR}/scripts/ld-version.sh)

if [[ $OWN_VER_LD -lt $MIN_REQ_LD ]]; then
	echo "You need at least $MIN_REQ and you have $OWN_BIN"
	exit 1
fi

echo ansible-playbook: OK
exit 0
