GITR_ARGS += gitr_fstype=ext4
GITR_ARGS += gitr_uses_no_devices='False'
GITR_ARGS += gitr_device=$(subst ",,$(CONFIG_GITR_EXT4_DEVICE))
GITR_ARGS += gitr_label=$(subst ",,$(CONFIG_GITR_EXT4_LABEL))
GITR_ARGS += gitr_mount_opts='$(subst ",,$(CONFIG_GITR_EXT4_MOUNT_OPTS))'
