GITR_ARGS += gitr_fstype=xfs
GITR_ARGS += gitr_uses_no_devices='False'

GITR_ARGS += gitr_device=$(subst ",,$(CONFIG_GITR_XFS_DEVICE))
GITR_ARGS += gitr_label=$(subst ",,$(CONFIG_GITR_XFS_LABEL))
GITR_ARGS += gitr_mount_opts='$(subst ",,$(CONFIG_GITR_XFS_MOUNT_OPTS))'
