#!/bin/bash

UPSTREAM="$HOME/linux-next/"

KCONFIG_UPSTREAM="conf.c"
KCONFIG_UPSTREAM="$KCONFIG_UPSTREAM confdata.c"
KCONFIG_UPSTREAM="$KCONFIG_UPSTREAM expr.c"
KCONFIG_UPSTREAM="$KCONFIG_UPSTREAM expr.h"
KCONFIG_UPSTREAM="$KCONFIG_UPSTREAM list.h"
KCONFIG_UPSTREAM="$KCONFIG_UPSTREAM lkc.h"
KCONFIG_UPSTREAM="$KCONFIG_UPSTREAM lkc_proto.h"
KCONFIG_UPSTREAM="$KCONFIG_UPSTREAM lxdialog"
KCONFIG_UPSTREAM="$KCONFIG_UPSTREAM mconf.c"
KCONFIG_UPSTREAM="$KCONFIG_UPSTREAM mconf-cfg.sh"
KCONFIG_UPSTREAM="$KCONFIG_UPSTREAM menu.c"
KCONFIG_UPSTREAM="$KCONFIG_UPSTREAM nconf.c"
KCONFIG_UPSTREAM="$KCONFIG_UPSTREAM nconf-cfg.sh"
KCONFIG_UPSTREAM="$KCONFIG_UPSTREAM nconf.gui.c"
KCONFIG_UPSTREAM="$KCONFIG_UPSTREAM nconf.h"
KCONFIG_UPSTREAM="$KCONFIG_UPSTREAM preprocess.c"
KCONFIG_UPSTREAM="$KCONFIG_UPSTREAM symbol.c"
KCONFIG_UPSTREAM="$KCONFIG_UPSTREAM util.c"
KCONFIG_UPSTREAM="$KCONFIG_UPSTREAM lexer.l"
KCONFIG_UPSTREAM="$KCONFIG_UPSTREAM parser.y"

for i in $KCONFIG_UPSTREAM; do
	cp -a $UPSTREAM/scripts/kconfig/$i .
done
