GITR_ARGS += gitr_fstype=btrfs
GITR_ARGS += gitr_uses_no_devices='False'
GITR_ARGS += gitr_device=$(subst ",,$(CONFIG_GITR_BTRFS_DEVICE))
GITR_ARGS += gitr_label=$(subst ",,$(CONFIG_GITR_BTRFS_LABEL))
GITR_ARGS += gitr_mount_opts='$(subst ",,$(CONFIG_GITR_BTRFS_MOUNT_OPTS))'

GITR_ENABLED_TEST_GROUPS += btrfs
