#!/bin/bash

source ${TOPDIR}/.config
source ${TOPDIR}/scripts/lib.sh

VAGRANTBOX=$CONFIG_VAGRANT_BOX
VBOXVERSION=$CONFIG_VAGRANT_BOX_VERSION

cat_template_nodes_sed $KDEVOPS_NODES_TEMPLATE > $KDEVOPS_NODES
