
source ${TOPDIR}/scripts/lib_terraform.sh
source ${TOPDIR}/scripts/aws/lib.sh
source ${TOPDIR}/scripts/gce/lib.sh
source ${TOPDIR}/scripts/azure/lib.sh
source ${TOPDIR}/scripts/openstack/lib.sh

cat_template_hosts_sed()
{
	cat $1 | sed -e \
		'
		s|@KDEVOPSPYTHONINTERPRETER@|'"$KDEVOPSPYTHONINTERPRETER"'|g;
		s|@KDEVOPSPYTHONOLDINTERPRETER@|'"$KDEVOPSPYTHONOLDINTERPRETER"'|g;
		' | cat -s
}

cat_template_nodes_sed()
{
	cat $1 | sed -e \
		'
		s|@VAGRANTBOX@|'"$VAGRANTBOX"'|g;
		s|@VBOXVERSION@|'$VBOXVERSION'|g;
		' | cat -s
}

cat_template_terraform_sed()
{
	cat $1 | sed -e \
		'
		s|@LIMITBOXES@|'"$LIMITBOXES"'|g;
		s|@LIMITNUMBOXES@|'"$LIMITNUMBOXES"'|g;
		s|@AWSREGION@|'$AWSREGION'|g;
		s|@AWSAVREGION@|'$AWSAVREGION'|g;
		s|@AWSNAMESEARCH@|'$AWSNAMESEARCH'|g;
		s|@AWSVIRTTYPE@|'$AWSVIRTTYPE'|g;
		s|@AWSAMIOWNER@|'$AWSAMIOWNER'|g;
		s|@AWSINSTANCETYPE@|'$AWSINSTANCETYPE'|g;
		s|@AZURERESOURCELOCATION@|'$AZURERESOURCELOCATION'|g;
		s|@AZUREVMSIZE@|'$AZUREVMSIZE'|g;
		s|@AZUREMANAGEDDISKTYPE@|'$AZUREMANAGEDDISKTYPE'|g;
		s|@AZUREIMAGEPUBLISHER@|'$AZUREIMAGEPUBLISHER'|g;
		s|@AZUREIMAGEOFFER@|'$AZUREIMAGEOFFER'|g;
		s|@AZUREIMAGESKU@|'$AZUREIMAGESKU'|g;
		s|@AZUREIMAGEVERSION@|'$AZUREIMAGEVERSION'|g;
		s|@AZURECLIENTCERTPATH@|'$AZURECLIENTCERTPATH'|g;
		s|@AZURECLIENTCERTPASSWD@|'$AZURECLIENTCERTPASSWD'|g;
		s|@AZUREAPPLICATIONID@|'$AZUREAPPLICATIONID'|g;
		s|@AZURESUBSCRIPTIONID@|'$AZURESUBSCRIPTIONID'|g;
		s|@AZURETENANTID@|'$AZURETENANTID'|g;
		s|@SSHCONFIGPUBKEYFILE@|'$SSHCONFIGPUBKEYFILE'|g;
		s|@SSHCONFIGUSER@|'$SSHCONFIGUSER'|g;
		s|@SSHCONFIGUPDATE@|'$SSHCONFIGUPDATE'|g;
		s|@SSHCONFIGFILE@|'$SSHCONFIGFILE'|g;
		s|@SSHCONFIGSTRICT@|'$SSHCONFIGSTRICT'|g;
		s|@SSHCONFIGBACKUP@|'$SSHCONFIGBACKUP'|g;
		' | cat -s
}
