# SPDX-License-Identifier GPL-2.0+
---
# Our sensible defaults for the gitr role.
#
# The default is to not run the gitr tests.
kdevops_run_gitr: False

kdevops_workflows_dedicated_workflow: false

gitr_test_list: ""
gitr_uses_no_devices: False

# NFS-specific defaults
gitr_nfs_use_kdevops_nfsd: false
gitr_nfs_section_v42: false
gitr_nfs_section_v41: false
gitr_nfs_section_v40: false
gitr_nfs_section_v3: false

# Family-dependent packages to install
gitr_os_family_packages:
  Debian:
    - cvs
    - cvsps
    - gcc
    - gettext
    - git-core
    - libcurl4-openssl-dev
    - libexpat1-dev
    - libssl-dev
    - libz-dev
    - perl
    - sqlite3
  RedHat:
    - cvs
    - cvsps
    - expat-devel
    - gcc
    - gettext
    - git-core
    - git-email
    - libcurl-devel
    - openssl-devel
    - perl-Memoize
    - perl-Test-Harness
    - perl-TAP-Harness-Archive
    - subversion
    - subversion-perl
    - zlib-devel
  Suse:
    - cvs
    - cvsps
    - gcc
    - gettext
    - git-core
    - libcurl-devel
    - libexpat-devel
    - libopenssl-1_1-devel
    - perl-Test-Harness
    - subversion
    - subversion-perl

# "test host" to "NFS version" mapping
gitr_nfs_vers_dict:
  nfs-v3:
    - "vers=3"
  nfs-v40:
    - "vers=4.0"
  nfs-v41:
    - "vers=4.1"
  nfs-v42:
    - "vers=4.2"
