---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "../extra_vars.yml"
      - "../extra_vars.yaml"
      - "../extra_vars.json"
      skip: true
  tags: vars

- include_role:
    name: create_data_partition
  tags: [ 'data_partition' ]

# Distro specific
- include_tasks: tasks/install-deps/main.yml

- name: git clone kdevops
  environment:
    GIT_SSL_NO_VERIFY:  true
  git:
    repo: "{{ kdevops_git }}"
    dest: "{{ kdevops_data }}"
    update: yes
    version: master
  tags: [ 'install', 'git']

- name: Copy over our .config
  copy:
    src: "{{ playbook_dir }}/../.config"
    dest: "{{ kdevops_dir }}"
  tags: [ 'install', 'root', 'config']

# We do this *after* the /data/ partition is set up so
# we can house the dbench source code there and so that
# we don't have to bother with the setup of that partition
# in the dbench role.
- name: Compile dbench from source if needed by the distribution
  include_role:
    name: compile_dbench
  vars:
    dbench_data: "{{ data_path }}/dbench"
    dbench_git: "{{ blktests_dbench_git }}"
  tags: [ 'oscheck', 'git', 'dbench']

- name: Remove any old blktrace as we always clone a fresh tree
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  file:
    path: "{{ blktrace_data }}"
    state: absent
  tags: [ 'git', 'blktests', 'blktrace' ]

- name: git clone blktrace
  git:
    repo: "{{ blktrace_git }}"
    dest: "{{ blktrace_data }}"
    update: yes
    version: master
  tags: [ 'git', 'blktests', 'blktrace' ]

- name: Get nproc
  command: "{{ num_jobs }}"
  tags: [ 'blktests', 'build', 'bltkrace' ]
  register: nproc

- name: Build blktrace
  tags: [ 'blktests', 'build', 'bltkrace' ]
  make:
    chdir: "{{ blktrace_data }}"
    jobs: "{{ nproc.stdout }}"

- name: Install blktrace
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "{{  make }} install"
  tags: [ 'blktests', 'install', 'root', 'blktrace' ]
  args:
    chdir: "{{ blktrace_data }}"

- name: Remove any old blktets as we always clone a fresh tree
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  file:
    path: "{{ blktests_data }}"
    state: absent
  tags: [ 'git', 'blktests']

- name: git clone blktests
  git:
    repo: "{{ blktests_git }}"
    dest: "{{ blktests_data }}"
    update: yes
    version: master
  tags: [ 'git', 'blktests']

- name: Build blktests
  tags: [ 'blktests', 'build']
  make:
    chdir: "{{ blktests_data }}"
    jobs: "{{ nproc.stdout }}"

- name: Install blktests
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "{{  make }} install"
  tags: [ 'blktests', 'install', 'root']
  args:
    chdir: "{{ blktests_data }}"

- name: git pull latest kdevops to ensure expunge list is up to date
  environment:
    GIT_SSL_NO_VERIFY:  true
  git:
    repo: "{{ kdevops_git }}"
    dest: "{{ kdevops_data }}"
    update: yes
    version: master
  tags: [ 'install', 'git', 'git_update', 'run_tests' ]

- name: Create a symbolic links needed
  become: yes
  become_method: sudo
  file:
    src: "{{ kdevops_dir }}/workflows/blktests/scripts/{{ item }}"
    dest: "{{ blktests_data_target }}/{{ item }}"
    state: link
  with_items:
    - "oscheck.sh"
  loop_control:
    label: "{{ item }}"
  tags: [ 'blktests', 'install' ]

- name: Disable multipathd service for srp blktests tests
  become: yes
  become_method: sudo
  systemd:
    name: multipathd
    enabled: no
    state: stopped
  tags: multipathd

- name: Reboot system before our test so we know everything is sane
  tags: [ 'blktests', 'run_tests', 'reboot' ]
  become: yes
  become_method: sudo
  reboot:
    post_reboot_delay: 10

- name: Set the path to blktests workflow
  set_fact:
    blktests_workflow_target: "../workflows/blktests/"
  tags: [ 'blktests', 'run_tests', 'copy_results', 'prior_run', 'print_results' , 'augment_expunge_list' ]

- name: Set the path where we collect our blktests results
  set_fact:
    blktests_results_target: "../workflows/blktests/results/"
    blktests_results_full_path: "{{ topdir_path }}/workflows/blktests/results/"
  tags: [ 'blktests', 'run_tests', 'copy_results', 'prior_run', 'print_results' , 'augment_expunge_list' ]

- name: Set the path where we collect blktests expunges
  set_fact:
    blktests_expunges_target: "../workflows/blktests/expunges/"
  tags: [ 'blktests', 'run_tests', 'copy_results', 'prior_run', 'print_results' , 'augment_expunge_list' ]

- name: Print uname for each host
  tags: [ 'blktests', 'run_tests' ]
  debug: var=ansible_kernel

- name: Get used target kernel version
  tags: [ 'blktests', 'copy_results', 'augment_expunge_list' ]
  command: "uname -r"
  register: uname_cmd

- name: Store last kernel variable
  set_fact:
    last_kernel: "{{ uname_cmd.stdout_lines | regex_replace('\\]') | regex_replace('\\[') | replace(\"'\",'') }}"
  tags: [ 'blktests', 'copy_results', 'augment_expunge_list' ]
  run_once: true

- name: Document used target kernel version
  local_action: "shell echo {{ last_kernel }} > {{ blktests_results_target }}/last-kernel.txt"
  tags: [ 'blktests', 'copy_results', 'augment_expunge_list' ]
  run_once: true

- name: Load configfs module
  tags: [ 'blktests', 'run_tests', 'configfs' ]
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "modprobe configfs"
  when:
    - kdevops_run_blktests|bool

- name: Clear out old results directory on target hosts
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  file:
    state: absent
    path: "{{ blktests_data_target }}/results/"
  tags: [ 'blktests', 'run_tests', 'clean_results' ]

- name: Verify target test devices are defined
  fail:
    msg: "The variable blktests_test_devs must be defined to run"
  when:
    - kdevops_run_blktests|bool
    - blktests_test_devs is not defined
  tags: [ 'blktests', 'run_tests' ]

- name: Verify target test device is not /dev/null
  fail:
    msg: "The variable blktests_test_devs must not be /dev/null"
  when:
    - blktests_test_devs == "/dev/null"
  tags: [ 'blktests', 'run_tests' ]

- name: Verify target test devices exist {{ blktests_test_devs }}
  vars:
    verify_dev_list: "{{ blktests_test_devs | regex_replace(' ', ' -a -e ') }}"
  tags: [ 'blktests', 'run_tests' ]
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "test -e {{ verify_dev_list }}"
  when:
    - kdevops_run_blktests|bool
    - blktests_test_devs|length != 0

- name: Verify target test devices are block devices {{ blktests_test_devs }}
  vars:
    verify_dev_list: "{{ blktests_test_devs | regex_replace(' ', ' -a -b ') }}"
  tags: [ 'blktests', 'run_tests' ]
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "test -b {{ verify_dev_list }}"
  when:
    - kdevops_run_blktests|bool
    - blktests_test_devs is defined
    - blktests_test_devs|length != 0

- name: Hint to watchdog tests are about to kick off
  local_action: file path="{{ blktests_workflow_target }}/.begin" state=touch
  tags: [ 'blktests', 'run_tests' ]
  when:
    - kdevops_run_blktests|bool
  run_once: true

- name: Enable low-level messages on console
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: sysctl kernel.printk="8 8 1 7"

- name: Check to see if dynamic test limit scope was set
  set_fact:
    dynamic_limit_tests: "{{ lookup('ansible.builtin.env', 'LIMIT_TESTS') }}"
  tags: [ 'blktests', 'run_tests', 'limit-tests' ]
  when:
    - not run_tests_on_failures|bool
    - kdevops_run_blktests|bool

- name: Allow dynamic test override
  set_fact:
    all_limit_tests: "{{ dynamic_limit_tests }}"
  tags: [ 'blktests', 'run_tests', 'limit-tests' ]
  when:
    - not run_tests_on_failures|bool
    - kdevops_run_blktests|bool
    - dynamic_limit_tests is defined
    - dynamic_limit_tests != None
    - dynamic_limit_tests | length > 0

- name: Empty out test limit if None is set
  set_fact:
    all_limit_tests: ""
  tags: [ 'blktests', 'run_tests', 'limit-tests' ]
  when:
    - not run_tests_on_failures|bool
    - kdevops_run_blktests|bool
    - all_limit_tests is defined
    - all_limit_tests == None

- name: Empty out test no limits have been set
  set_fact:
    all_limit_tests: ""
  tags: [ 'blktests', 'run_tests', 'limit-tests' ]
  when:
    - not run_tests_on_failures|bool
    - kdevops_run_blktests|bool
    - all_limit_tests is undefined

- name: Run oscheck-get-failures.sh to get list of known failed tests
  vars:
    group: "{{ ansible_host | regex_replace('blktests-') | regex_replace(kdevops_host_prefix + '-') | regex_replace('-dev') | regex_replace('-', '_') }}"
  tags: [ 'blktests', 'run_tests' ]
  command: "{{ kdevops_data }}/workflows/blktests/scripts/oscheck-get-failures.sh --test-group {{ group }}"
  args:
    chdir: "{{ blktests_data_target }}"
  register: failed_tests_limit
  when:
    - run_tests_on_failures|bool
    - kdevops_run_blktests|bool

- name: Inform user no failures are known
  fail:
    msg: "No known failures for this run! Go find bugs!"
  tags: [ 'blktests', 'run_tests' ]
  when:
    - run_tests_on_failures|bool
    - kdevops_run_blktests|bool
    - failed_tests_limit.stdout | replace('\n', ' ') | length == 0

- name: Set test limit to known failed tests
  set_fact:
    all_limit_tests: "{{ failed_tests_limit.stdout | replace('\n', ' ') }}"
  tags: [ 'blktests', 'run_tests' ]
  when:
    - run_tests_on_failures|bool
    - kdevops_run_blktests|bool

- name: Print list of test limits for this run
  debug:
    msg: "all_limit_tests: {{ all_limit_tests }}"
  tags: [ 'blktests', 'run_tests', 'limit-tests' ]
  when:
    - kdevops_run_blktests|bool
    - all_limit_tests is defined
    - all_limit_tests != None
    - all_limit_tests | length > 0

- name: Stop blktests if we're debbugging limit_tests
  ansible.builtin.meta: end_play
  tags: [ 'blktests', 'run_tests' ]
  when:
    - blktests_skip_run|bool

- name: Run blktests using oscheck.sh
  vars:
    group: "{{ ansible_host | regex_replace('blktests-') | regex_replace(kdevops_host_prefix + '-') | regex_replace('-dev') | regex_replace('-', '_') }}"
  tags: [ 'blktests', 'run_tests' ]
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "./oscheck.sh --print-start --print-done --test-group {{ group }} {{ oscheck_extra_args }} {{ all_limit_tests }}"
  ignore_errors: yes
  no_log: True
  args:
    chdir: "{{ blktests_data_target }}"
  environment:
    TEST_DEVS: "{{ blktests_test_devs }}"
    LIMIT_TESTS: "{{ all_limit_tests }}"
  when:
    - kdevops_run_blktests|bool

- name: Remove watchdog hint that tests have started
  local_action: file path="{{ blktests_workflow_target }}/.begin" state=absent
  tags: [ 'blktests', 'run_tests' ]
  when:
    - kdevops_run_blktests|bool
  run_once: true

- name: Clean up our localhost results/last-run directory
  local_action: file path="{{ blktests_results_target }}/{{ item }}" state=absent
  with_items:
    - "last-run"
  loop_control:
    label: "{{ item }}"
  run_once: true
  tags: [ 'blktests', 'copy_results', 'clean_local_results' ]

- name: Look for results for the last run
  tags: [ 'blktests', 'copy_results' ]
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  find:
    paths: "{{ blktests_data_target }}/results/"
    recurse: yes
    patterns: "*"
  register: last_run_results

- name: Copy all test results
  tags: [ 'blktests', 'copy_results' ]
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  fetch:
    src: "{{ item.path }}"
    dest: "{{ blktests_results_target }}/last-run/{{ item.path | regex_replace(blktests_data_target + 'results/' | regex_escape()) | regex_replace('^/', '') }}"
    flat: yes
  with_items: "{{ last_run_results.files }}"
  loop_control:
    label: "{{ item.path | regex_replace(blktests_data_target + 'results/' | regex_escape()) | regex_replace('^/', '') }}"
  when:
    - last_run_results.matched > 0

- name: Augment expunge list just run git diff after this to see new failures found
  local_action: "shell ./python/workflows/blktests/augment_expunge_list.py {{ blktests_results_target }}/last-run/ {{ blktests_expunges_target }}"
  tags: [ 'blktests', 'copy_results', 'augment_expunge_list' ]
  run_once: true

- name: Copy last-run files to results directory for target kernel and in place only bad and dmesg files
  local_action: "shell ./python/workflows/blktests/gen-results-dir.py"
  tags: [ 'blktests', 'copy_results', 'print_results', 'augment_expunge_list' ]
  run_once: true

- name: Print blktests new expunge files for which are not yet committed
  local_action: "shell ./python/workflows/blktests/get_new_expunge_files.py {{ blktests_expunges_target }}"
  register: new_expunges
  tags: [ 'blktests', 'copy_results', 'print_results', 'augment_expunge_list' ]
  run_once: true

- name: Inform user if new expunge files have been found
  run_once: true
  tags: [ 'blktests', 'copy_results', 'augment_expunge_list' ]
  debug:
    msg: "New expunge files found: {{ new_expunges.stdout_lines }}"
  when:
    - new_expunges.stdout != 0

# You are encouraged to commit the compressed results of failed tests
# so we keep an archive
- name: Compress results {{ blktests_results_full_path }}.xz
  community.general.archive:
    path: "{{ blktests_results_full_path }}/{{ last_kernel }}"
    dest: "{{ blktests_results_full_path }}/{{ last_kernel }}.xz"
    format: xz
  run_once: true
  tags: [ 'blktests', 'copy_results', 'augment_expunge_list' ]
  delegate_to: localhost
