ifeq (y,$(CONFIG_FSTESTS_TMPFS_SECTION_DEFAULT))
FSTESTS_ARGS += fstests_tmpfs_section_default=True
endif
ifeq (y,$(CONFIG_FSTESTS_TMPFS_SECTION_NOSWAP))
FSTESTS_ARGS += fstests_tmpfs_section_noswap=True
endif
ifeq (y,$(CONFIG_FSTESTS_TMPFS_SECTION_HUGE))
FSTESTS_ARGS += fstests_tmpfs_section_huge=True
endif
