#!/bin/bash
# SPDX-License-Identifier: copyleft-next-0.3.1

source ${TOPDIR}/.config
source ${TOPDIR}/scripts/lib.sh

FSTESTSTESTDEV="$CONFIG_FSTESTS_TEST_DEV"
FSTESTSTESTDEVZNS="$CONFIG_FSTESTS_TEST_DEV_ZNS"
FSTESTSDIR="$CONFIG_FSTESTS_TEST_DIR"
FSTESTSSCRATCHDEVPOOL="$CONFIG_FSTESTS_SCRATCH_DEV_POOL"
FSTESTSSCRATCHDEVPOOLZNS="$CONFIG_FSTESTS_SCRATCH_DEV_POOL_ZNS"
FSTESTSSCRATCHMNT="$CONFIG_FSTESTS_SCRATCH_MNT"
FSTESTSLOGWRITESDEV="$CONFIG_FSTESTS_LOGWRITES_DEV"
FSTESTSSCRATCHLOGDEV="$CONFIG_FSTESTS_SCRATCH_LOGDEV"

if [[ "$FSTYP" == "xfs" ]]; then
	FSTESTSSCRATCHRTDEV="$CONFIG_FSTESTS_SCRATCH_RTDEV"
fi

cat_fstests_config_sed $KDEVOPS_FSTESTS_CONFIG_TEMPLATE > $KDEVOPS_FSTESTS_CONFIG
